sudo: required
services:
  - docker

before_install:
  - docker build -t papiyinks/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true papiyinks/docker-react yarn run test -- --coverage
